### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by bhavyaidr**
Process of  Dockerizing a Spring Boot Application and creating a fat JAR to run from command line.

### CODE REVIEW

**Review by prernablr92 — COMMENTED** [review]
You should have created a Dockerfile and added the dockerization code into that.

**Comment by bhavyaidr** [comment]
Ohh..okay
So should I create a Dockerfile now ?

**Comment by prernablr92** [comment]
Nope I merged it now.

**Comment by bhavyaidr** [comment]
okay

**Pull request merged**
